#!/bin/bash

cvt () {
    convert -resize $2 $1.png res/$3 || exit
}

cvt icon 38x38 drawable-hdpi/ic_stat_playing.png
cvt icon 36x36 drawable-hdpi-v11/ic_stat_playing.png
cvt icon 24x38 drawable-hdpi-v9/ic_stat_playing.png
cvt icon 25x25 drawable-mdpi/ic_stat_playing.png
cvt icon 24x24 drawable-mdpi-v11/ic_stat_playing.png
cvt icon 16x25 drawable-mdpi-v9/ic_stat_playing.png
cvt icon 50x50 drawable-xhdpi/ic_stat_playing.png
cvt icon 48x48 drawable-xhdpi-v11/ic_stat_playing.png
cvt icon 32x50 drawable-xhdpi-v9/ic_stat_playing.png

cvt bob 38x38 drawable-hdpi/ic_stat_downloaded.png
cvt bob 36x36 drawable-hdpi-v11/ic_stat_downloaded.png
cvt bob 24x38 drawable-hdpi-v9/ic_stat_downloaded.png
cvt bob 25x25 drawable-mdpi/ic_stat_downloaded.png
cvt bob 24x24 drawable-mdpi-v11/ic_stat_downloaded.png
cvt bob 16x25 drawable-mdpi-v9/ic_stat_downloaded.png
cvt bob 50x50 drawable-xhdpi/ic_stat_downloaded.png
cvt bob 48x48 drawable-xhdpi-v11/ic_stat_downloaded.png
cvt bob 32x50 drawable-xhdpi-v9/ic_stat_downloaded.png

cvt icon 72x72 drawable-hdpi/ic_launcher.png
cvt icon 48x48 drawable-mdpi/ic_launcher.png
cvt icon 96x96 drawable-xhdpi/ic_launcher.png

# 128x128 drawable-hdpi/forward.png
# 128x128 drawable-hdpi/forward_pressed.png
# 128x128 drawable-hdpi/pause.png
# 128x128 drawable-hdpi/pause_pressed.png
# 128x128 drawable-hdpi/play.png
# 128x128 drawable-hdpi/play_pressed.png
# 128x128 drawable-hdpi/rewind.png
# 128x128 drawable-hdpi/rewind_pressed.png
